### ISSUE TITLE
Uploading a CAR file fails with "Error: 524: Origin Time-out"

### ISSUE THREAD

**Issue by skogard** [nftstorage/nft.storage#660]
I have been having trouble uploading a CAR file built from a folder that contains 1000 JSON files. This is not a big file (458KB) and I don't know why it never goes through.

Just to be clear, the code works for smaller CAR files (with like 5 items in a folder), but just stops working at certain point as I increase the number of files in the folder.

here's the code to replicate:

```javascript
require('dotenv').config()
const { CarIndexedReader } = require('@ipld/car')
const { NFTStorage, File } = require('nft.storage')
const token = process.env.NFT_STORAGE_KEY
const storage = new NFTStorage({ token })
const upload = async (folderPath) => {
  const carReader = await CarIndexedReader.fromFile(`${process.cwd()}/output.car`)
  const cid = await storage.storeCar(carReader)
  console.log("CID", cid)
}
(async () => {
  await upload("metadata2")
  process.exit()
})();
```

The `storage.storeCar()` method just hangs. I wait for about 10 minutes and it crashes with the following error:

```
Uploading...
/Users/a/ipfscar/node_modules/nft.storage/dist/src/lib.cjs:111
      throw new Error(result.error.message)
            ^

Error: 524: Origin Time-out
    at Function.storeBlob (/Users/a/ipfscar/node_modules/nft.storage/dist/src/lib.cjs:111:13)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async RetryOperation._fn (/Users/a/ipfscar/node_modules/p-retry/index.js:50:12) {
  attemptNumber: 6,
  retriesLeft: 0
}
```

I've also attached the car file I'm using (unzip the file before using):

[output.car.zip](https://github.com/nftstorage/nft.storage/files/7400800/output.car.zip)

**Comment by davidpurkiss** [comment]
Hey. I'm running into this as well. 524 is a Cloudflare specific response code and you can see what it says here.

https://support.cloudflare.com/hc/en-us/articles/115003011431#524error

Should this endpoint be behind Cloudflare? I think you should expect uploads to take longer than 100 seconds in general. The doc above says,

>If you regularly run HTTP requests that take over 100 seconds to complete (for example large data exports), move those processes behind a subdomain not proxied (grey clouded) in the Cloudflare DNS app.

**Comment by Gozala** [comment]
I can confirm that error occurs on cluster upload 

https://github.com/nftstorage/nft.storage/blob/ea7485213e940d608e5b21dfa94f7bce43fb735c/packages/api/src/routes-v1/nfts-upload.js#L72

So it seems that cluster takes over 100s to respond, so CF just errors a request.

Per linked cloudflare page  it looks like we could bump the `proxy_read_timeout` 

> Enterprise customers can increase the 524 timeout up to 6000 seconds using the [proxy_read_timeout API endpoint](https://api.cloudflare.com/#zone-settings-change-proxy-read-timeout-setting).

Which may be a reasonable bandaid, however we may also want to consider not worker based upload routes.

**Comment by Gozala** [comment]
I have uploaded same car to a local cluster and here are the results I'm seeing

```
curl -o /dev/null -X POST http://user:secretà127.0.0.1:9094/addç?formatç=car -F "file=à/Users/gozala/Downloads/output.car"
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  447k    0   111  100  447k      3  12988  0:00:35  0:00:35 --:--:--    28
```

Which is just 35secs well below 100

**Comment by Gozala** [comment]
Running same against the cluster nft.storage talks to takes quite a bit longer 190secs which is above 100s

```
curl -o /dev/null -X POST https://nft2.storage.ipfscluster.io/api/add\?format\=car -F "file=@/Users/gozala/Downloads/output.car" -H "Authorization: Basic $AUTH"
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  447k    0   111  100  447k      0   2347  0:03:15  0:03:15 --:--:--    22
```

**Comment by Gozala** [comment]
Issue was fixed and should address the problem in the next deployment

**Comment by skogard** [comment]
Hi @Gozala thank you for the update, when will the next deployment be? I would like to test it out.

**Comment by Gozala** [comment]
@skogard it was deployed and issue is fixed, I just run example from linked observable and can confirm it works

**Comment by arigbs** [comment]
There is still an issue, at least for uploading multiple images. 
Code shared by @skogard currently works fine for json files of up to 1,000 in a directory, but not for image files of a large number. I was only able to get it to work for 2 image files, so that shows ordinarily it should work for images. It fails for 10 image files and upwards with an error that says:  Unexpected token < in JSON at position 0. I noticed the output.car file that gets built as part of the process gets as large as over 3.2GB when trying to upload images, compared to 447kb for the json files. The 3.2GB large car gets uploaded but can't be opened to reveal the images.

**Comment by arigbs** [comment]
> There is still an issue, at least for uploading multiple images. Code shared by @skogard currently works fine for json files of up to 1,000 in a directory, but not for image files of a large number. I was only able to get it to work for 2 image files, so that shows ordinarily it should work for images. It fails for 10 image files and upwards with an error that says: Unexpected token < in JSON at position 0. I noticed the output.car file that gets built as part of the process gets as large as over 3.2GB when trying to upload images, compared to 447kb for the json files. The 3.2GB large car gets uploaded but can't be opened to reveal the images.

Apparently file size matters quite a bit. I managed to compress the files from over 2mb each to just over 200kb using irfanview without losing resolution. Upload to nft.storage this time was reasonably fast without error. Files didn't open immediately on ipfs, had to give it some hours to propagate, but now all the 1,000 jpegs are loading without issues.

Putting this out there for anyone else there struggling with loading a large number of images from a directory. @skogard's code linked above and his [nftp](https://github.com/factoria-org/nftp) are about the only working implementations of nft.storage I've found for loading directories with large number of files to nft.storage, so shout out to him for sharing.

**Comment by Gozala** [comment]
Thanks @arigbs for the updates. If you could provide a reproducible test case with specific image files we could try look into that as well to try and fix that. The smaller the case the better. If you could fork and update that observable example that would be ideal.

**Comment by fdchiu** [comment]
I am seeing the issue very often when I upload an ipfs car directory with 6000 (small) files. The car file itself is only <10MB.

**Comment by alanshaw** [comment]
are you able to attach it here so we can look into it?

**Comment by fdchiu** [comment]
[metadata.car.zip](https://github.com/nftstorage/nft.storage/files/8447449/metadata.car.zip)
Here is the car file. Please rename it back to .car since .car type is not allowed to be attached on GitHub. 
I tried about 4 times and it was successful at the last try.

**Comment by theshadowagent** [comment]
I'm also having this problem with 10.000 JSONs, but don't have it with 1,000 JSONs (though it still takes a while to upload 200kb .CAR folder)

**Comment by mounir82** [comment]
Hi everyone.  i get the same error when i upload 50000 json files equal to 100Megabyte.  The script create car for 50000 json files . But the upload of the car file fails. Thank you for your help.
file:///D:/fullproject/myapp/node_modules/nft.storage/src/lib.js:159
              throw new Error(result.error.message)
                    ^

Error: 524:
    at pRetry.retries (file:///D:/601-700/myapp/node_modules/nft.storage/src/lib.js:159:21)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async RetryOperation._fn (D:\fullproject\601-700\myapp\node_modules\p-retry\index.js:50:12) {
  attemptNumber: 6,
  retriesLeft: 0
}

**Comment by caffeinum** [comment]
As a workaround, I upload big directories directly to Pinata now. Had a lot of struggle doing this from browser via POST request.

In the end, using their example https://docs.pinata.cloud/api-pinning/pin-file#pinning-a-directory-example and intercepting request from their frontend helped me to break it down

Here's a part of their code (sourcemapped so took directly from Chrome at https://app.pinata.cloud/pinmanager)

```javascript
const handleV1Upload = (selectedFiles, customName, wrapWithDirectory) => {
    const data = new FormData();
    if (customName && customName !== '') {
        const metadata = JSON.stringify({
            name: customName
        });
        data.append(getLabel(false, "metadata"), metadata);        
    } 

    if (selectedFiles.length > 0) {
        Array.from(selectedFiles).forEach((file) => {
            data.append(getLabel(false, "file"), file);
        });              
    } else {
        data.append(getLabel(false, "file"), selectedFiles[0], selectedFiles[0].name);
    }
    
    // in the end, I didn't use this param
    if (wrapWithDirectory === true) {
        const pinataOptions = JSON.stringify({
            wrapWithDirectory: true
        });
        data.append(getLabel(false, "options"), pinataOptions);
    }

    return data;
}

export const handleUpload = (selectedFiles, customName, wrapWithDirectory, progressCallback, submarine) => async (dispatch) => {
    try {
        let data;
        if(submarine) {
            data = handleV2Upload(selectedFiles, customName, wrapWithDirectory, submarine)                
        } else {
            data = handleV1Upload(selectedFiles, customName, wrapWithDirectory);
        }

        const customConfig = {
            progress: true,
            progressCallback: progressCallback
        };

        // different structure on v1 and v2 
        // for v2 -> always return an array of items
        // for v1 -> if there is only one item as object
        let response, uploadedItem;
        if(submarine) {
            response = await (await uploadToManagedAPI('content', data, customConfig)).json();
            uploadedItem = response.items[0];
        } else {
            response = await (await uploadToAPI('pinning/pinFileToIPFS', data, customConfig)).json();
            uploadedItem = response;
        }
        // ... ui processing
};

export const uploadToAPI = async (route, body) => {
    try {
        const config = await getApiConfig();
        //  TODO when fetch supports progress, let's return a progress indicator
        return await ky(`${apiBaseURL}/${route}`, {
            method: 'POST',
            headers: config.headers,
            body: body, 
            timeout: 2147483647
        }).catch(async(e) => {
            const error = await e.response.text();
            return Promise.reject({
                response: {data: JSON.parse(error)}
            });
        });
    } catch (error) {
        throw error;
    }
}
```

P.S. probably not the best place to post it
